apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: my-encrypted-secret
    namespace: default
spec:
    suspend: false
    secretTemplates:
        - name: demo-app-secret
          stringData:
            SECRET1: ENC[AES256_GCM,data:K0jg2hWCRNdWkIiUgi4x7RLQLAul3GN4,iv:M78zDodF4T653omnTQrR2ACegVlClwSTAr627n2Mtf0=,tag:Wsk0dOqS63u2OzwTgVJ/rw==,type:str]
            SECRET2: ENC[AES256_GCM,data:Fqie2xP70FHVHc3IPOTd7vXaPFhWJexXNa+cPqIBRUdLilb/mi3OGV0=,iv:KaKNoZEKciwXHCfYXzy6YyfqL3qrmaGIrdv9e5EXRhY=,tag:uHdG1/Cp1MdRzVC7lnzWfw==,type:str]
sops:
    age:
        - recipient: age1xpqy6dqglmjcwkkyy7a9tm2u26r7r6svnyjsw97vmwsjmvxzz97s6h6gqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU01iY2VVVENWY1pYM0ox
            NmdmK0lDcW5NRCsreXhsbGIweUFMWFFVYUFFCmRkbEwrVG9UdWVyWWhWdUJET3pS
            aEtCbHVuRmNtQkZzQWpRWXBEUTdVVmcKLS0tIG9hV0xDVTZ3cGRmVmR4NVJKMFlY
            NFQzcUZqMUFRVm9KdDJheUJpRFZwVHMK5ji3wzoF1HmwVH6z+cmen13df409jjrg
            dNzxcmT95CYsu9999tPwPDTAyrK1KuIiSPucC8U1cuJ9WcBR00MXMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T03:48:25Z"
    mac: ENC[AES256_GCM,data:hxKnsVwJNfrrBFC85LpVLeWEv/OpnXNGVPE/EcGUb26WBv5TS3gMlMXDhKf0JP8D9DThGSYo2gdw1Fb2o/lvyjEvCAwV/n/UKKu9xy6Pze8s34CTufR2wZYdvIV30UWcqz1poAOSyg8ych4XgxTMYERLUNm8mydFF/qxUyWJfSc=,iv:WDIHo9geL+7dZNGhboRfae0uOjWW8vtp9Ug7B1bM+w4=,tag:5S6HilJpIPRPaJBME2MUwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
