apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default  # Must match SopsSecret namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo
          image: nginx
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: my-app-secret  # Must match secretTemplates.name in SopsSecret