apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: my-encrypted-secret
    namespace: default
spec:
    suspend: false
    secretTemplates:
        - name: my-app-secret
          type: Opaque
          data:
            #ENC[AES256_GCM,data:5PTXtcE6eKRp,iv:rzM4j5o+aqDkIeoOyGb4e++1+3uZCeOcMLMrR2Ii0/Q=,tag:FG9KmpHEK2QxLZzodD2SGg==,type:comment]
            username: ENC[AES256_GCM,data:Dtw3sfLCxkKA0Em2,iv:GKP4g0HpRN37GBIOp11Rd368dCNguWzJiLFnZLYT820=,tag:3YnrHgDnpyiL5tK6kumbbw==,type:str]
            #ENC[AES256_GCM,data:mQVS0m3bpu20,iv:k1S8qvwcXxYR5c9NDtyA8A+uMW9UHPWWesFXnjtR5HQ=,tag:w+Ii3STUeqQtbLWvvD473w==,type:comment]
            password: ENC[AES256_GCM,data:SWPF+iTcktgSFJME,iv:z2LAMdMxowiYS2RuYKnG4FFK4anYkIRS7zD/lr17ZTY=,tag:ofLEAzgacX8PzWzO6p+nvg==,type:str]
sops:
    age:
        - recipient: age1xpqy6dqglmjcwkkyy7a9tm2u26r7r6svnyjsw97vmwsjmvxzz97s6h6gqf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZDR6YmpjbWVndEZYVzRp
            bTlPUTBxdkxlWk9TNkFVeGdJWVNKekhLL3pBCnJWQk9VTFFLV3ltci9rU0ptVG9z
            dWxwd2J5NWlpWXJraXdXTVpUWmh2T2cKLS0tIC9RblNSV1RaVHArb1JuR21hUFl5
            cmFZcGlxYngzclhDUTJUV09NaTkzelEK+QimO7GBFPOFmgPiHy+zmZL44I7ZVugC
            A2zZifD/dtvsjLhew2nNcD/b4BI3TP891nffEgVP7OZXiNuRsHqj9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T03:25:31Z"
    mac: ENC[AES256_GCM,data:xdvgRihpvn91GaLCBzj9Ghj3pOsfYPFW2FR2XlWfQvNHgXme/+mEPlXILrw4YM00kYv6GtY9XikmrQCzJLuxM9pSQWgGzUzW3HTbomA4oHr8p49OV5waRrQwnBuSeG7Zwdi9iyYitQOf8HF+Tx7B1FnpfHRBW5YJ//EC8SfBr8A=,iv:AwGWz671gQaQH8zAE4OaNqrbqma5CJ/slq6XfWuCgRI=,tag:bkixwgtOpfHbbBWcaZZQyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
